version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=brainweb
      - POSTGRES_USER=brainweb
    volumes:
      - pgtest-data:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  pgtest-data:
